
import { ServiceArea } from '../types';

export const SUGGESTED_PROMPTS_BY_AREA: Record<ServiceArea, string[]> = {
  [ServiceArea.VENTURE_CAPITAL]: [
    // General & Introduction (Re-checked and expanded)
    "What is venture capital (VC) financing and how does it work in India?",
    "What are the typical stages of startup funding (Seed, Series A, B, C)?",
    "Explain the role and expectations of a VC firm post-investment.",
    "Key differences between Angel Investors, Micro VCs, and larger VC funds?",
    "What is a Term Sheet and what are its binding/non-binding provisions?",
    "Describe the due diligence process from a VC's perspective in India.",
    "Common valuation methodologies for early-stage startups in India?",
    "How does equity dilution impact founders and early employees?",
    "What are the standard rights VCs seek in Indian deals (e.g., information, board seat)?",
    "What is a capitalization table (cap table) and why is it crucial?",
    "What is the difference between pre-money and post-money valuation?",
    "What are the common mistakes founders make when pitching to VCs?",
    "What is a venture debt and how does it differ from equity financing?",
    "What are alternative funding options for startups in India besides VC?",
    "What are the pros and cons of bootstrapping vs. seeking VC funding?",
    "Explain the concept of 'dry powder' in VC context.",
    "What is a 'lead investor' and their role in a funding round?",
    "What are current trends in the Indian VC landscape?",
    "How long does a typical VC funding round take from start to finish?",
    "What are the legal costs associated with a VC funding round?",
    // Agreements & Documentation (Re-checked and expanded)
    "What are the essential clauses in a Term Sheet for an Indian startup?",
    "Key provisions to negotiate in a Shareholders' Agreement (SHA)?",
    "Key provisions in a Share Subscription Agreement (SSA)?",
    "Importance of 'Representations and Warranties' by founders?",
    "Explain 'Conditions Precedent' (CPs) and 'Conditions Subsequent' (CSs) in funding.",
    "What are 'Pre-emptive Rights' and 'Right of First Refusal' (ROFR)?",
    "Difference between 'Drag-Along' and 'Tag-Along' rights?",
    "Explain 'Anti-Dilution Protection': Full Ratchet vs. Broad-Based Weighted Average.",
    "What is a 'Liquidation Preference'? (e.g., 1x participating/non-participating).",
    "What are 'Information Rights' and 'Inspection Rights' for VCs?",
    "Key elements of a Founders' Agreement in an Indian context?",
    "What is a 'Side Letter' and when is it used in VC deals?",
    "How are disputes typically resolved as per VC agreements in India?",
    "What are the standard 'Closing Deliverables' in a funding round?",
    "Explain 'Control Provisions' and 'Affirmative Vote Matters' for investors.",
    "What is a 'Pay-to-Play' provision in VC financing?",
    "What are 'milestone-based' tranches in funding agreements?",
    "Importance of 'Governing Law' and 'Jurisdiction' clauses in cross-border deals.",
    "What is an 'Indemnification' clause and its typical caps/baskets?",
    "How are 'Escrow Accounts' used in VC funding rounds?",
    // Startup Specific (Re-checked and expanded)
    "Optimal legal structure for a tech startup in India (Pvt Ltd, LLP)?",
    "Step-by-step process for incorporating a Private Limited Company in India.",
    "Key initial ROC (Registrar of Companies) compliances for a new startup?",
    "How to structure an Employee Stock Option Plan (ESOP) under Indian law?",
    "What is 'Sweat Equity' and how can it be issued to founders/advisors?",
    "Strategies for protecting a startup's Intellectual Property (IP) from day one.",
    "Essential terms for a Co-founder Agreement to prevent future disputes.",
    "What is 'Vesting of Shares' (time-based, cliff) for founders and ESOPs?",
    "Legal implications of pivoting a startup's business model in India.",
    "How to legally handle founder departures or disputes?",
    "Requirements for Foreign Direct Investment (FDI) in Indian startups under FEMA.",
    "What is downstream investment and its compliance?",
    "What is a Convertible Note? Key terms (discount rate, valuation cap).",
    "What is a SAFE (Simple Agreement for Future Equity) and its use in India?",
    "Pros and cons of various debt instruments for startups (venture debt, debentures).",
    "How does a 'Bridge Round' work and when is it needed?",
    "Common red flags for investors during legal due diligence of a startup.",
    "What are the legal and financial implications of a 'Down Round'?",
    "Legal aspects of an 'Acqui-hire' in the Indian startup ecosystem.",
    "Typical 'Exit Strategies' for VCs and founders (IPO, M&A, secondary sale).",
    "What is 'Startup India Initiative' and its benefits for recognized startups?",
    "How to obtain DPIIT recognition for a startup?",
    "What are 'Angel Networks' and how do they operate in India?",
    "What are the legal aspects of a 'friends and family' funding round?",
    "How to handle related party transactions in a startup context?",
    // Advanced & Regulatory (Re-checked and expanded)
    "Explain SEBI (Alternative Investment Funds) Regulations, 2012 for VC funds.",
    "Tax implications of ESOPs for employees and the company in India?",
    "What is 'Angel Tax' (Section 56(2)(viib)) and recent exemptions/changes?",
    "Annual ROC compliances for a Pvt Ltd company (DIR-3 KYC, DPT-3, MSME-1, AOC-4, MGT-7).",
    "Consequences of non-compliance with terms of funding agreements.",
    "Process for increasing Authorized Share Capital of a company.",
    "How to issue Rights Shares or Bonus Shares in a startup?",
    "Key legal considerations when preparing for a Series A funding round.",
    "Legal differences between Cumulative/Non-Cumulative Preference Shares and Equity Shares.",
    "How to structure an Advisory Board and agreements for advisors?",
    "Key legal documents needed for a VC pitch deck?",
    "Most common legal mistakes Indian startups make in early stages?",
    "Effective negotiation strategies for a Term Sheet with a VC.",
    "Role and responsibilities of legal counsel in a VC funding round.",
    "Key terms to scrutinize in an Incubation/Accelerator Agreement.",
    "Ensuring compliance with Indian labor laws for a rapidly growing startup.",
    "Data privacy (DPDP Act) compliance for Indian tech startups.",
    "How to issue shares for consideration other than cash (e.g., for IP, services)?",
    "Process for changing the Registered Office of a company within or across states.",
    "Director Identification Number (DIN) and Digital Signature Certificate (DSC) requirements.",
    "Board meeting procedures, quorum, and minutes preparation as per Companies Act, 2013.",
    "Maintenance of statutory registers (e.g., Register of Members, Directors).",
    "IP assignment from founders/employees to the company: Process and importance.",
    "Legal aspects of forming a Joint Venture (JV) for a startup.",
    "'Know Your Customer' (KYC) and Anti-Money Laundering (AML) for investors.",
    "Restrictions on transfer of shares in a private limited company in India.",
    "Legal disclaimers and considerations for a startup's website and marketing materials.",
    "Dealing with an investor's request for early exit or liquidity.",
    "'Key Person' insurance provisions in VC investment agreements.",
    "'Most Favored Nation' (MFN) clauses in Term Sheets: Implications.",
    "Structuring investments from international accelerator programs: FEMA and tax.",
    "Impact of significant beneficial ownership (SBO) rules on startups.",
    "Regulations around crowdfunding and peer-to-peer lending for startups in India.",
    "How to best prepare for an investor's legal due diligence checklist?",
    "'Lock-in' periods for shares: For founders, investors, pre-IPO.",
    "Initial steps a startup should take upon receiving a legal notice.",
    "Legal implications of using open-source software in proprietary products.",
    "Key clauses in vendor and supplier contracts for a startup.",
    "Legal checklist for a startup planning international expansion from India.",
    "'Reverse Vesting' for founders: How it works and why it's used.",
    "Protecting confidential information during discussions with potential investors (NDAs).",
    "Enforceability of 'Non-Compete' and 'Non-Solicit' clauses for founders/employees.",
    "Process for voluntary winding up / striking off a private limited company.",
    "Issuing debentures (convertible/non-convertible) as a startup: Legal process.",
    "Key recent legal/regulatory updates impacting startups in India.",
    "Can a foreign national be a full-time director in an Indian startup?",
    "What are the compliances under Shops and Establishment Act for startups?",
    "Handling a situation if a co-founder is non-performing or wishes to exit.",
    "Common pitfalls in SAFEs and Convertible Notes if not structured carefully.",
    "Legal considerations for a B2B SaaS startup vs. a B2C product startup.",
    "Structuring a Pilot Agreement or Beta Testing Agreement with early customers.",
    "Implications of misrepresentation or fraud during a funding round.",
    "Typical legal fee structures for startup advisory and fundraising legal work.",
    "Managing 'Board Observer' rights vs. 'Board Director' rights for investors."
  ],
  [ServiceArea.MERGERS_ACQUISITIONS]: [
    // Introduction & Types (Re-checked and expanded)
    "What are the main types of M&A transactions in India (merger, demerger, acquisition)?",
    "Differentiate between a merger, an acquisition, and an amalgamation under Indian law.",
    "Key differences and implications of a Share Purchase vs. an Asset Purchase/BTA.",
    "What is a 'Slump Sale' as defined under the Indian Income Tax Act?",
    "Strategic rationale behind M&A deals (e.g., market entry, consolidation, technology).",
    "Distinguish between a 'Friendly Takeover' and a 'Hostile Takeover' (rare in India).",
    "Outline the typical lifecycle/stages of an M&A transaction in India.",
    "What is a Leveraged Buyout (LBO) and its applicability in India?",
    "Explain a 'Reverse Merger' and its typical objectives.",
    "Key roles and responsibilities of advisors in an M&A deal (legal, financial, tax).",
    "What is a 'Creeping Acquisition' under SEBI Takeover Code?",
    "What is a 'Management Buyout (MBO)' or 'Management Buy-in (MBI)'?",
    "Difference between horizontal, vertical, and conglomerate mergers?",
    "What are 'synergies' in M&A and how are they typically valued?",
    "What is a 'carve-out' transaction?",
    "Key considerations for cross-border M&A involving an Indian company.",
    "What is a 'distressed M&A' and its unique challenges?",
    "How does a 'strategic alliance' or 'joint venture' differ from an M&A?",
    "What are 'PIPE' (Private Investment in Public Equity) deals?",
    "What is the role of a merchant banker in M&A involving listed companies?",
    // Due Diligence (Re-checked and expanded)
    "Scope and objectives of Legal Due Diligence in an Indian M&A context.",
    "Key areas covered in a comprehensive Legal DD checklist for an Indian target.",
    "What is Financial Due Diligence? Tax Due Diligence? Operational Due Diligence?",
    "How to effectively prepare and manage a Due Diligence Questionnaire (DDQ)?",
    "Common 'Red Flags' or material issues identified during Legal DD in India.",
    "Significance and best practices for managing a Virtual Data Room (VDR) in M&A.",
    "Specific challenges in conducting DD for a cross-border M&A deal.",
    "Legal consequences of inadequate or flawed due diligence.",
    "How is Intellectual Property (IP) Due Diligence conducted in technology M&A?",
    "Explain 'Material Adverse Change' (MAC) / 'Material Adverse Effect' (MAE) clauses.",
    "What is environmental due diligence and its importance?",
    "How to conduct anti-bribery and anti-corruption (ABAC) due diligence?",
    "What is HR due diligence and what does it cover?",
    "What are 'change of control' clauses and how are they identified in DD?",
    "How is litigation and dispute DD conducted?",
    "What is the importance of verifying title to shares/assets?",
    "How to assess regulatory compliance during DD?",
    "What is the role of forensic due diligence in specific cases?",
    "How are findings from DD typically addressed in the transaction documents?",
    "What is 'seller due diligence' or 'vendor due diligence'?",
    // Deal Structuring & Agreements (Re-checked and expanded)
    "How to structure an M&A deal for optimal tax efficiency in India?",
    "Key provisions of a Non-Disclosure Agreement (NDA) specific to M&A.",
    "What is a Letter of Intent (LOI) or Term Sheet in M&A? Binding aspects?",
    "Essential clauses in a Share Purchase Agreement (SPA) under Indian law.",
    "Essential clauses in an Asset Purchase Agreement (APA) / Business Transfer Agreement (BTA).",
    "Nature and scope of 'Representations and Warranties' in M&A agreements.",
    "What are 'Indemnification' clauses? (Caps, baskets, survival periods).",
    "'Conditions Precedent' (CPs) to Closing an M&A deal: Examples.",
    "'Closing Conditions' vs. 'Closing Actions': Clarify the distinction.",
    "Use and structure of an Escrow Agreement in M&A for purchase price/indemnity.",
    "Explain 'Earn-out' provisions and their structuring challenges.",
    "Non-compete and Non-solicit clauses: Enforceability under Indian contract law.",
    "Legal framework for employee transfers in M&A (Section 25FF of ID Act).",
    "Role and importance of 'Disclosure Schedules' in M&A agreements.",
    "Treatment of liabilities in a Share Purchase vs. an Asset Purchase.",
    "What is 'Locked Box' vs. 'Completion Accounts' mechanism for purchase price adjustment?",
    "How to draft 'Further Assurances' clauses effectively?",
    "What are 'assignment and change of control' provisions in M&A context?",
    "How to structure 'holdback' provisions for indemnification claims?",
    "What is a 'Transitional Services Agreement' (TSA)?",
    // Regulatory Approvals (Re-checked and expanded)
    "Overview of regulatory approvals required for M&A in India (CCI, NCLT, SEBI, RBI).",
    "Role of the Competition Commission of India (CCI) in merger control.",
    "Current monetary thresholds for CCI notification in India.",
    "Process for NCLT approval for schemes of merger/amalgamation under Companies Act.",
    "SEBI Takeover Code implications for acquisitions involving listed Indian companies.",
    "Specific approvals needed for M&A in regulated sectors (e.g., banking, insurance, telecom).",
    "FEMA implications for cross-border M&A (inbound and outbound).",
    "Stamp duty calculation and payment on M&A transaction documents in India.",
    "Key tax implications of M&A: Capital Gains, GST, tax on slump sale.",
    "Process for obtaining foreign investment approvals (e.g., from DPIIT, MHA if applicable).",
    "What is 'Form FC-TRS' and 'Form FC-GPR' reporting to RBI?",
    "What are the implications of Press Note 3 (2020) for FDI in M&A?",
    "What is 'Indirect Transfer' of shares and its tax implications in India?",
    "How are 'Conditions Subsequent' to regulatory approvals handled?",
    "What are the consequences of 'gun jumping' under Indian competition law?",
    // Post-Merger & Special Situations (Re-checked and expanded)
    "Key legal considerations for successful Post-Merger Integration (PMI).",
    "Process for integrating employee contracts, benefits, and HR policies post-acquisition.",
    "Harmonizing corporate policies and compliance programs after a merger.",
    "Common types of post-closing disputes in M&A and how to mitigate them.",
    "What is a 'Demerger' (Spin-off, Split-off) and its structuring under Indian law?",
    "Legal framework and process for a Management Buyout (MBO) in India.",
    "Key legal considerations when acquiring a distressed company or assets under IBC.",
    "Impact of the Insolvency and Bankruptcy Code (IBC) on M&A strategies.",
    "Structuring a Joint Venture (JV) as an alternative to a full acquisition.",
    "Protecting minority shareholder rights in an M&A transaction.",
    "Process and legality of 'Squeeze-out' of minority shareholders in India.",
    "What is a 'Scheme of Arrangement' under the Companies Act and its uses beyond M&A?",
    "Common valuation methods used in Indian M&A deals.",
    "Difference between Enterprise Value (EV) and Equity Value.",
    "Key negotiation points in an M&A SPA from a Seller's perspective.",
    "Key negotiation points in an M&A SPA from a Buyer's perspective.",
    "Managing confidentiality and information flow during M&A negotiations.",
    "Role of Investment Bankers and other advisors in facilitating M&A.",
    "Common legal pitfalls to avoid in executing M&A transactions in India.",
    "Impact of M&A on corporate governance structure and board composition.",
    "Handling integration of IT systems, data, and IP post-merger: Legal aspects.",
    "Specific challenges in acquiring a family-owned business in India.",
    "'Warranty and Indemnity' (W&I) Insurance in Indian M&A: Availability and use.",
    "Process and compliances for M&A involving a listed Indian company.",
    "Requirements for disclosure of related party M&A transactions.",
    "Reviewing 'Material Contracts' during DD: What to look for?",
    "Implications of 'Change of Control' clauses in material contracts of the target.",
    "Managing existing litigation and contingent liabilities of the target company.",
    "Process for amalgamation of a subsidiary company with its parent company.",
    "Ensuring proper transfer and protection of Intellectual Property in M&A.",
    "Legal considerations for 'Divestitures' or 'Spin-offs' of business units.",
    "Managing public relations and stakeholder communications during an M&A deal.",
    "'Break Fees' or 'Termination Fees' in M&A agreements: Enforceability.",
    "Ensuring compliance with anti-bribery and corruption laws during cross-border M&A.",
    "Typical post-closing obligations and covenants for buyer and seller.",
    "Legal mechanisms for unwinding an M&A deal if it fails or faces issues.",
    "Recent trends and landmark M&A deals in the Indian market.",
    "SEBI (LODR) Regulations compliances applicable to M&A involving listed entities.",
    "Role and importance of 'Fairness Opinions' in M&A transactions.",
    "Sector-specific M&A considerations (e.g., Pharma, Fintech, E-commerce).",
    "Legal differences and complexities in acquiring a public vs. a private company in India.",
    "Managing data privacy (DPDP Act) issues during M&A DD and post-merger integration.",
    "Key terms in a Merger Agreement or Scheme of Amalgamation document.",
    "Structuring 'Deferred Consideration' or 'Contingent Consideration' in M&A.",
    "Implications of GAAR (General Anti-Avoidance Rule) on M&A tax structuring.",
    "How to effectively deal with unknown or contingent liabilities of the target?",
    "Process for effecting a name change of a company post-acquisition/merger.",
    "Common methods for financing an acquisition in India (debt, equity, internal accruals).",
    "Valuing intangible assets (brand, IP, goodwill) in an M&A context.",
    "Key legal documents required for each stage of an M&A deal (LOI to Closing).",
    "Explain 'Specific Performance' as a remedy in M&A agreement disputes."
  ],
  [ServiceArea.REGULATORY_GUIDANCE]: [
    // General Regulatory Landscape (Re-checked and expanded)
    "Which are the key regulatory bodies a new business in India must be aware of?",
    "How can a business identify all applicable central and state regulations in India?",
    "Outline the general process for obtaining necessary licenses and permits for a business.",
    "What are the typical penalties for non-compliance with major Indian business regulations?",
    "How to conduct a comprehensive regulatory compliance audit for my company?",
    "Core principles of corporate governance for unlisted companies under Companies Act, 2013?",
    "Explain the functions of the Ministry of Corporate Affairs (MCA) and ROC.",
    "Key ongoing compliance requirements under the Indian Companies Act, 2013 for Pvt Ltd Co.",
    "Best practices for staying updated on frequent changes in Indian regulations?",
    "What is the Digital Personal Data Protection (DPDP) Act, 2023 and its applicability?",
    "How to map regulatory obligations to business processes?",
    "What is 'regulatory sandbox' and its availability in India (e.g., for Fintech)?",
    "What are the common challenges faced by businesses in navigating Indian regulations?",
    "How to develop a compliance calendar for a business?",
    "What is the role of a compliance officer in an organization?",
    "What are 'Standard Operating Procedures' (SOPs) for ensuring regulatory compliance?",
    "How to manage third-party vendor compliance risk?",
    "What are the regulations around 'Know Your Customer' (KYC) for non-financial businesses?",
    "What are the implications of 'Significant Beneficial Ownership' (SBO) rules?",
    "How to handle conflicts between different regulatory requirements?",
    // Sector-Specific Regulations (Re-checked and expanded)
    "Key SEBI (LODR) regulations for listed companies beyond M&A (e.g., disclosures, governance).",
    "RBI guidelines for Fintech companies (e.g., payment aggregators, digital lending).",
    "E-commerce regulations in India (Consumer Protection E-commerce Rules, FDI Policy).",
    "Regulatory framework for Telecom companies by TRAI and DoT.",
    "FSSAI licensing and compliance for food manufacturing, processing, and retail businesses.",
    "Drug and Cosmetic Act regulations for pharmaceutical manufacturing and sales.",
    "Environmental regulations (Air, Water, Waste Management) for manufacturing units.",
    "Key labor law compliances for factories vs. commercial establishments in India.",
    "Regulations and licensing for Non-Banking Financial Companies (NBFCs).",
    "IRDAI regulations impacting insurance companies and intermediaries.",
    "Regulations for Real Estate developers under RERA (Real Estate Regulation and Development Act).",
    "What are the regulations for online gaming and fantasy sports in India?",
    "Specific regulations for EdTech platforms in India.",
    "Regulations for HealthTech services, including telemedicine and e-pharmacies.",
    "What are the regulations for renewable energy projects in India?",
    "Compliance requirements for logistics and warehousing businesses.",
    "Regulations applicable to media and entertainment companies (broadcast, OTT).",
    "What are the key compliances for a hospital or healthcare facility?",
    "Regulations for companies operating in Special Economic Zones (SEZs).",
    "What are the regulations concerning drone operations in India?",
    // FEMA & Foreign Investment (Re-checked and expanded)
    "To whom does the Foreign Exchange Management Act (FEMA), 1999 apply?",
    "Detailed rules for Foreign Direct Investment (FDI) under different sectors in India.",
    "Distinguish between Automatic Route and Government Approval Route for FDI.",
    "What are 'downstream investments' under FEMA and their associated compliances?",
    "Step-by-step process for reporting FDI to RBI via the FIRMS portal (SMF, ARF).",
    "Regulations for External Commercial Borrowings (ECB): Eligible borrowers, lenders, end-uses.",
    "Overseas Direct Investment (ODI) regulations for Indian entities investing abroad.",
    "Process and compliance for setting up a Liaison Office, Branch Office, or Project Office.",
    "Rules for repatriation of profits, dividends, and disinvestment proceeds by foreign investors.",
    "Transfer pricing regulations under Income Tax Act and their interplay with FEMA.",
    "What is 'round tripping' under FEMA and its implications?",
    "Regulations for investment by Non-Resident Indians (NRIs) and Overseas Citizens of India (OCIs).",
    "What are Foreign Portfolio Investment (FPI) regulations?",
    "Compounding of contraventions under FEMA: Process and implications.",
    "What are the regulations for issuance and transfer of shares to non-residents?",
    // Data Privacy & Cybersecurity (Re-checked and expanded)
    "Key obligations of 'Data Fiduciaries' and 'Data Processors' under DPDP Act?",
    "What constitutes 'Personal Data' and 'Sensitive Personal Data' under Indian law?",
    "Requirements for obtaining valid 'Consent' under the DPDP Act, 2023.",
    "Data Breach notification obligations under DPDP Act and CERT-In directions.",
    "CERT-In directions regarding cybersecurity incidents, logging, and reporting.",
    "Relevant provisions of the Information Technology Act, 2000 concerning cybercrimes and intermediaries.",
    "How to draft a comprehensive Privacy Policy compliant with DPDP Act and IT Rules?",
    "Rules and restrictions for cross-border transfer of personal data from India.",
    "What are the 'Rights of Data Principals' (e.g., access, correction, erasure) under DPDP Act?",
    "Penalties for non-compliance with DPDP Act and other data protection laws.",
    "What are 'Data Protection Impact Assessments' (DPIA) and when are they required?",
    "Cybersecurity best practices for businesses operating in India.",
    "What are the legal requirements for data localization in specific sectors (e.g., payments)?",
    "How to handle employee data privacy in compliance with Indian laws?",
    "What are the legal aspects of using cookies and online tracking technologies?",
    // Competition Law (Re-checked and expanded)
    "Objectives and key provisions of the Competition Act, 2002.",
    "What constitutes an 'anti-competitive agreement' (horizontal and vertical)?",
    "Defining and proving 'abuse of dominant position' under Competition Act.",
    "How are cartels defined and penalized under Indian competition law?",
    "Merger control provisions: notification thresholds and review process by CCI.",
    "Investigative powers and procedures of the Competition Commission of India (CCI).",
    "Penalties and remedies for violations of competition law in India.",
    "What is a 'Leniency Program' or 'Lesser Penalty' regime under Competition Act?",
    "Process for filing an information or complaint with the CCI.",
    "'Resale Price Maintenance', 'Tie-in Arrangements', 'Exclusive Supply/Distribution' as vertical restraints.",
    "What is 'predatory pricing' by a dominant enterprise?",
    "How does competition law apply to digital markets and platforms?",
    "What are 'hub and spoke' cartels?",
    "Role of economic analysis in competition law assessments.",
    "What are interim relief measures that CCI can grant?",
    // Other Key Regulatory Areas (Re-checked and expanded)
    "Key features and processes under the Insolvency and Bankruptcy Code (IBC), 2016.",
    "Who can initiate Corporate Insolvency Resolution Process (CIRP) and on what grounds?",
    "AML/KYC (Anti-Money Laundering/Know Your Customer) requirements beyond financial institutions.",
    "POSH Act (Sexual Harassment of Women at Workplace) compliances: ICC, training, reporting.",
    "Core labor law compliances (EPF, ESI, Gratuity, Minimum Wages, Maternity Benefit).",
    "CSR (Corporate Social Responsibility) spending and reporting requirements under Companies Act.",
    "Advertising standards and codes by ASCI; implications of misleading advertisements.",
    "Best practices for handling regulatory inspections and investigations by authorities.",
    "Legal Metrology Act and Packaged Commodities Rules: Labeling and measurement compliance.",
    "Process and benefits of obtaining an Import-Export Code (IEC).",
    "Regulations for 'Related Party Transactions' under Companies Act and SEBI (LODR).",
    "Legal requirements and procedures for conducting Annual General Meetings (AGM) / Extraordinary General Meetings (EGM).",
    "Compliance with anti-bribery and anti-corruption laws (Prevention of Corruption Act).",
    "Requirements for establishing and implementing a Whistle-blower Policy.",
    "Regulations for Payment Aggregators and Payment Gateways by RBI.",
    "Impact of RERA on real estate developers and projects: Registration and compliance.",
    "SEBI (Prohibition of Insider Trading) Regulations: Key prohibitions and disclosures.",
    "Legal requirements for digital lending apps and platforms: RBI guidelines.",
    "Emerging ESG (Environmental, Social, and Governance) reporting norms in India.",
    "Significance of Udyam/MSME registration and associated benefits/compliances.",
    "Regulations governing NGOs, charitable trusts, and Section 8 companies.",
    "Compliance with local municipal laws (e.g., trade licenses, building permits).",
    "Key regulations for Telemedicine and Digital Health services in India.",
    "Legal and regulatory requirements for E-pharmacies and online sale of medicines.",
    "How to proactively manage regulatory risks in a new or expanding business venture?",
    "Process for 'Compounding of Offences' under Companies Act, FEMA, etc.",
    "Key provisions of the Consumer Protection Act, 2019 impacting businesses.",
    "Procedure for obtaining various No Objection Certificates (NOCs) from government bodies.",
    "Waste management rules (e-waste, plastic waste, biomedical waste) and pollution control norms.",
    "Food Safety and Standards Act (FSSAI) labeling and packaging laws.",
    "Legal process and considerations for a product recall in India.",
    "Regulations for conducting clinical trials for drugs and medical devices.",
    "Legal requirements for operating cloud kitchens and food delivery services.",
    "Fire safety regulations and compliance for commercial establishments.",
    "Regulations for Direct Selling Entities and Multi-Level Marketing (MLM) in India.",
    "Key aspects of the Right to Information (RTI) Act applicable to certain businesses.",
    "Compliance with regulations for handling and storage of hazardous substances.",
    "SEBI regulations for Investment Advisers and Research Analysts.",
    "Regulatory framework for Alternative Investment Funds (AIFs) in India."
  ],
  [ServiceArea.INTELLECTUAL_PROPERTY]: [
    // Trademarks (Re-checked and expanded)
    "What is a trademark? What types of marks can be registered in India (word, logo, sound)?",
    "How to conduct a comprehensive trademark search in India (online database, market search)?",
    "Step-by-step process for trademark registration in India from application to registration.",
    "Understanding the 45 classes of goods and services under the NICE classification.",
    "Proper usage of ™, ℠, and ® symbols in relation to trademarks.",
    "Duration of trademark registration in India and the process for renewal.",
    "What constitutes trademark infringement? Examples and legal remedies.",
    "Explain the concept of 'Passing Off' and its difference from infringement.",
    "How to respond to a trademark examination report (objections) or an opposition?",
    "What are 'Well-Known Trademarks' and their enhanced protection in India?",
    "What is a 'collective mark' or a 'certification mark'?",
    "How to register a trademark internationally (Madrid Protocol)?",
    "What is trademark dilution and how is it prevented?",
    "Can a color or a shape be registered as a trademark?",
    "What is 'secondary meaning' or 'acquired distinctiveness' for trademarks?",
    // Copyrights (Re-checked and expanded)
    "What is copyright? What original literary, dramatic, musical, artistic works are protected?",
    "Is copyright registration mandatory in India? What are its benefits?",
    "Detailed process for copyright registration in India with the Copyright Office.",
    "What is the term of copyright protection for different types of works in India?",
    "What acts constitute copyright infringement of various works?",
    "Explain 'Fair Use' or 'Fair Dealing' exceptions under Indian Copyright Act.",
    "What are 'Moral Rights' of an author (right of paternity, right of integrity)?",
    "Process and key terms for licensing or assigning a copyright.",
    "Procedure for issuing a takedown notice for online copyright infringement in India.",
    "How is software (source code, object code, UI) protected under copyright law?",
    "What are 'related rights' or 'neighboring rights' in copyright (performers, broadcasters)?",
    "Can ideas or concepts be copyrighted?",
    "What is a 'compulsory license' for copyrighted works?",
    "How to deal with copyright infringement on social media platforms?",
    "What is the 'first sale doctrine' or 'doctrine of exhaustion' in copyright?",
    // Patents (Re-checked and expanded)
    "What is a patent? What are the criteria for patentability (novelty, inventive step, industrial applicability)?",
    "What inventions are not patentable in India (Section 3 & 4 of Patents Act)?",
    "How to conduct a thorough patent search (prior art search)?",
    "Process for filing a patent application in India (provisional vs. complete specification).",
    "What is patent prosecution? Stages involved (examination, hearing, grant).",
    "Term of a patent in India and requirements for maintenance (renewal fees).",
    "What constitutes patent infringement? Direct, indirect, contributory.",
    "What are 'Compulsory Licensing' provisions under the Indian Patents Act?",
    "How to file an international patent application via PCT (Patent Cooperation Treaty)?",
    "Key elements and drafting considerations for a patent specification (claims, description).",
    "What is 'Freedom to Operate' (FTO) analysis and its importance?",
    "What is a 'patent of addition'?",
    "What are pre-grant and post-grant oppositions to a patent application/patent?",
    "What is the Bolar exemption or research exemption in patent law?",
    "How are pharmaceutical patents and software patents treated in India?",
    // Designs & Other IP (Re-checked and expanded)
    "What is an Industrial Design? What aesthetic features are protected in India?",
    "Step-by-step process for design registration with the Indian Patent Office.",
    "What is a Trade Secret? How can it be legally protected without registration?",
    "What are Geographical Indications (GIs)? Examples and registration process in India.",
    "Protection of Semiconductor Integrated Circuit Layout Designs in India.",
    "How are Plant Varieties protected in India (Protection of Plant Varieties and Farmers' Rights Act)?",
    "What is 'confidential information' and how does it differ from trade secrets?",
    "What are domain names and how do they relate to trademarks (cybersquatting)?",
    "How to protect a business model or a unique concept?",
    "What is 'personality rights' or 'publicity rights' and its protection in India?",
    // IP Agreements & Transactions (Re-checked and expanded)
    "Key clauses in an IP Assignment Agreement (trademarks, copyrights, patents).",
    "Drafting an effective IP Licensing Agreement (exclusive/non-exclusive, territory, royalty).",
    "What is a Technology Transfer Agreement and its IP implications?",
    "IP aspects of a Franchise Agreement (trademark license, know-how).",
    "Checklist for IP Due Diligence in M&A, investments, or collaborations.",
    "Pros and cons of an IP Holding Company structure for Indian businesses.",
    "Common methodologies for valuing Intellectual Property assets.",
    "Structuring royalty payments in IP license agreements (fixed, percentage, tiered).",
    "IP ownership clauses in Software Development Agreements (client vs. developer).",
    "Key IP considerations in SaaS (Software as a Service) agreements.",
    "What are IP indemnification clauses in commercial agreements?",
    "What is an 'escrow agreement' for source code?",
    "How to manage joint ownership of IP?",
    "What are 'open innovation' models and their IP implications?",
    "What are 'patent pools' and 'cross-licensing' agreements?",
    // Media & Technology Law (overlapping with IP) (Re-checked and expanded)
    "Overview of key media laws in India (Prasar Bharati Act, Cable TV Networks Act, etc.).",
    "Content regulations for online platforms under IT (Intermediary Guidelines) Rules, 2021.",
    "Advertising laws and self-regulation by ASCI (Advertising Standards Council of India).",
    "Civil and criminal aspects of Defamation Law in India (online and offline).",
    "Legal issues related to User-Generated Content (UGC) and platform liability.",
    "Legal and ethical guidelines for Influencer Marketing in India.",
    "Data privacy for media/tech companies under DPDP Act and other regulations.",
    "IT Act, 2000: Key provisions for intermediaries, e-signatures, cybercrimes.",
    "Drafting enforceable End User License Agreements (EULAs) for software/apps.",
    "Compliance issues with various Open-Source Software (OSS) licenses (GPL, MIT, Apache).",
    "What are OTT platform regulations in India?",
    "What are the laws related to online news portals and digital media ethics?",
    "What are the legal implications of deepfakes and synthetic media?",
    "How is online gaming regulated in India (skill vs. chance)?",
    "What are the Cinematograph Act and its relevance to film certification?",
    // Enforcement & Disputes (Re-checked and expanded)
    "Drafting an effective Cease and Desist Notice for IP infringement.",
    "Civil remedies for IP infringement (injunctions, damages, accounts of profits).",
    "Criminal remedies for trademark and copyright infringement in India.",
    "Current status and functioning of Commercial Courts for IP disputes.",
    "Role of Customs authorities in preventing import/export of counterfeit goods (IPR Enforcement Rules).",
    "IP Arbitration and Mediation as alternative dispute resolution mechanisms.",
    "What is a 'John Doe Order' (Anton Piller order) in IP enforcement?",
    "Strategies for combating online IP infringement (e-commerce, social media).",
    "Resolving cybersquatting and domain name disputes (UDRP, INDRP).",
    "Estimating costs associated with IP litigation in Indian courts.",
    "Protecting IP when collaborating with universities or research institutions.",
    "Conducting an IP audit: Process, benefits, and key areas of focus.",
    "Developing a comprehensive IP strategy aligned with business goals.",
    "Common IP mistakes and how startups/SMEs can avoid them.",
    "Ensuring IP ownership from employees, consultants, and contract developers.",
    "'Prior Art' search and its significance in patent invalidation.",
    "India's position on 'First to File' vs. 'First to Invent' for patents.",
    "IP ownership and infringement issues related to AI-generated content and inventions.",
    "Dealing with 'Patent Trolls' or Non-Practicing Entities (NPEs).",
    "Specific IP challenges and strategies for pharmaceutical companies in India.",
    "Comprehensive IP protection strategy for a mobile application.",
    "Broadcasting rights for sports events and their protection.",
    "Copyright issues in the music industry (mechanical rights, performing rights, sync licenses).",
    "Legal implications of 'Sampling' in music creation.",
    "'Fair Dealing' for criticism, review, reporting under Copyright Act.",
    "Protecting Traditional Knowledge (TK) and Traditional Cultural Expressions (TCEs).",
    "Border control measures by customs for IP protection: Practical aspects.",
    "Taxation of IP transactions (royalties, assignment fees) in India.",
    "Strategies for securing and enforcing IP rights in international markets.",
    "Using the Madrid Protocol for international trademark registration: Pros and Cons.",
    "International copyright protection under Berne Convention and WIPO treaties.",
    "IP landscaping as a tool for R&D planning and competitive intelligence.",
    "Role of IP in securing investment and enhancing business valuation.",
    "Drafting and implementing an effective internal IP Policy for a company.",
    "IP considerations in Joint Development Agreements and R&D collaborations.",
    "Protecting trade secrets when employees leave or join competitors.",
    "Using IP as collateral for securing loans or financing.",
    "Recent landmark judgments and amendments in Indian IP laws.",
    "Impact of digital transformation and emerging technologies (Metaverse, NFTs) on IP.",
    "Addressing IP issues in cloud computing agreements and data hosting."
  ],
  [ServiceArea.VIRTUAL_GENERAL_COUNSEL]: [
    // Contract Management (Re-checked and expanded)
    "Can you review this [specific type] agreement and highlight key risks/areas for negotiation?",
    "What are the essential elements of a legally binding contract under Indian Contract Act?",
    "How to draft a comprehensive Master Service Agreement (MSA) for ongoing services?",
    "Best practices for drafting and using Non-Disclosure Agreements (NDAs).",
    "Common pitfalls and negotiation points in SaaS subscription agreements.",
    "Key legal considerations when negotiating commercial lease agreements in India.",
    "Relationship between a Statement of Work (SOW) and an MSA: How to ensure consistency?",
    "Legal implications of an unsigned contract or agreement by email exchange.",
    "Steps to implement an effective contract lifecycle management (CLM) system.",
    "Are 'Limitation of Liability' clauses always enforceable? What are reasonable caps?",
    "Drafting and negotiating 'Indemnity' and 'Hold Harmless' clauses.",
    "What is a 'Force Majeure' clause and its relevance in current times?",
    "How to ensure proper contract execution (stamping, signatures, witnesses)?",
    "What are 'boilerplate' clauses and which ones need careful review?",
    "How to manage contract renewals and terminations effectively?",
    // Corporate Governance & Compliance (Re-checked and expanded)
    "What are the mandatory annual ROC filings for a private/public limited company in India?",
    "Procedure for conducting valid Board Meetings and General Meetings (AGM/EGM).",
    "Fiduciary duties and liabilities of Directors under the Companies Act, 2013.",
    "Maintenance of statutory registers (Members, Directors, Charges, etc.): Requirements.",
    "Overview of corporate secretarial compliances for an Indian entity.",
    "Identifying and managing 'Related Party Transactions' as per Companies Act and SEBI LODR.",
    "Best practices for drafting accurate and compliant Minutes of meetings.",
    "Process for appointment, resignation, or removal of a Director or KMP.",
    "Applicability and compliance with CSR (Corporate Social Responsibility) provisions.",
    "Establishing and operationalizing a Whistle-blower/Vigil Mechanism policy.",
    "What are 'Director KYC' (DIR-3 KYC) and 'Active Company Tagging' (INC-22A/ACTIVE) compliances?",
    "What is 'Significant Beneficial Ownership' (SBO) reporting?",
    "How to handle 'Oppression and Mismanagement' issues under Companies Act?",
    "What are the requirements for internal financial controls (IFC)?",
    "Compliance with Secretarial Standards issued by ICSI.",
    // Employment & HR Law (Re-checked and expanded)
    "Key clauses to include in an Employment Agreement for different employee levels.",
    "Difference between an Offer Letter and an Appointment Letter: Legal standing.",
    "POSH Act compliances: ICC formation, training, annual reporting, policy.",
    "Legal procedure for employee termination (misconduct, retrenchment, resignation).",
    "Enforceability of Non-compete, Non-solicit, and Confidentiality clauses for employees in India.",
    "Compliance with Provident Fund (PF), ESI, Payment of Gratuity Act, Bonus Act.",
    "Contents of an Employee Handbook/HR Policy Manual compliant with Indian laws.",
    "Legal aspects of performance appraisals, promotions, and disciplinary actions.",
    "Managing legal distinctions and risks with contract employees vs. permanent employees.",
    "Compliance with Shops and Establishments Act of the respective state.",
    "Maternity Benefit Act: Entitlements and employer obligations.",
    "What are the laws related to child labor and prevention?",
    "How to handle employee data privacy under DPDP Act?",
    "What are the legal requirements for background verification of employees?",
    "How to structure an effective employee grievance redressal mechanism?",
    // Day-to-Day Operations & Risk Management (Re-checked and expanded)
    "How to effectively respond to a legal notice or a show-cause notice?",
    "When and how to send a formal legal notice to another party?",
    "Ensuring day-to-day operational compliance with DPDP Act, 2023.",
    "Legal requirements for a company's website: Terms of Use, Privacy Policy, Cookie Policy.",
    "How to conduct a periodic legal health check-up or compliance audit for a business?",
    "Identifying and mitigating key legal risks for an e-commerce or online business.",
    "Developing and implementing a practical legal risk management framework.",
    "What types of business insurance policies are essential or advisable in India?",
    "Best practices for handling customer complaints that have legal implications.",
    "Legal review of marketing and advertising materials to ensure compliance (ASCI, Consumer Protection Act).",
    "What are the stamping requirements for various commercial documents in India?",
    "How to deal with regulatory inspections by tax authorities or other bodies?",
    "What are the legal implications of using electronic signatures (e-signatures)?",
    "How to manage legal risks associated with social media usage by the company/employees?",
    "What are the 'Know Your Distributor/Agent' compliance requirements?",
    // Dispute Resolution (Re-checked and expanded)
    "What are the recommended first steps when a commercial dispute arises?",
    "Mediation vs. Arbitration vs. Litigation: Pros and cons for different situations.",
    "Drafting an effective multi-tiered dispute resolution clause in commercial contracts.",
    "Value and process of pre-litigation legal advice and strategy.",
    "How to manage ongoing litigation effectively and control costs?",
    "Typical costs and timelines involved in commercial litigation in Indian courts.",
    "When is it appropriate to send a formal Demand Letter before initiating legal action?",
    "Strategies for negotiating a favorable settlement in a commercial dispute.",
    "Understanding the concept of 'Limitation Period' for various legal claims.",
    "Criteria for selecting and managing external counsel for specialized litigation.",
    "What is 'interim relief' in litigation and when can it be sought?",
    "What is the Commercial Courts Act and how does it expedite disputes?",
    "How to enforce a judgment or arbitral award in India?",
    "What are the grounds for challenging an arbitral award?",
    "What is 'Without Prejudice' communication in settlement negotiations?",
    // Business Advisory (Re-checked and expanded)
    "Legal implications of expanding business operations to new states within India.",
    "Structuring a Joint Venture or Strategic Alliance: Key legal considerations.",
    "Legal checklist before launching a new product or service in the Indian market.",
    "Measures to protect confidential business information and trade secrets from misuse.",
    "Benefits and compliance requirements for MSME (Udyam) registration.",
    "Ensuring compliance with all necessary local licenses and permits (e.g., trade, health).",
    "Key terms and negotiation points in Distribution Agreements or Agency Agreements.",
    "Ownership and protection of Intellectual Property created by employees or contractors.",
    "Legal aspects of setting up and running a franchise business in India.",
    "How to prepare for and manage a potential regulatory audit or inspection by authorities?",
    "Developing Standard Operating Procedures (SOPs) that ensure legal compliance.",
    "Legal review and risk mitigation in supply chain contracts and vendor agreements.",
    "Implementing a company's ESG (Environmental, Social, Governance) policy: Legal aspects.",
    "Procedure and best practices for conducting internal investigations (e.g., fraud, misconduct).",
    "Legal requirements for data retention and record management policies.",
    "Managing legal compliance for a remote or hybrid workforce in India.",
    "Compliance with e-invoicing, GST returns, and other indirect tax requirements.",
    "Developing a legal response plan for cybersecurity incidents and data breaches.",
    "What kind of legal and compliance training should employees receive regularly?",
    "Ensuring marketing claims and product labeling are legally compliant.",
    "Legal risks and considerations when using third-party software, APIs, or cloud services.",
    "Policy for handling unsolicited business proposals or IP submissions from external parties.",
    "Key legal differences and considerations: Partnership Firm vs. LLP vs. Private Limited Company.",
    "Legal process for dissolution of a Partnership Firm or winding up an LLP.",
    "Legal requirements for conducting online contests, giveaways, or sweepstakes in India.",
    "Managing online reputation and legally addressing defamatory content or false reviews.",
    "Legal implications of using website cookies and obtaining user consent.",
    "Ensuring Terms and Conditions for online services are clear, comprehensive, and enforceable.",
    "Legal review of a startup's pitch deck and representations made to potential investors.",
    "Implementing and monitoring a Conflict of Interest policy for directors and employees.",
    "Best practices for maintaining corporate records from a legal and evidentiary standpoint.",
    "Ensuring effectiveness of anti-corruption and anti-bribery policies and training.",
    "Legal requirements and best practices for board diversity and inclusion initiatives.",
    "Legal and logistical management of a product recall or service disruption.",
    "Understanding vicarious liability: When is a company liable for acts of its employees?",
    "Ensuring influencer marketing campaigns comply with ASCI guidelines and consumer law.",
    "Legal considerations for data residency and sovereignty when using global cloud services.",
    "Drafting and implementing an effective Code of Conduct and Ethics for the company.",
    "Legal requirements for shareholder communications and investor relations (for unlisted closely held too).",
    "Responding to information requests from statutory authorities or law enforcement.",
    "Reviewing and invoking 'Force Majeure' clauses in contracts during unforeseen events.",
    "Process for amending a company's Memorandum of Association (MOA) or Articles of Association (AOA)."
  ],
  [ServiceArea.LEGAL_TECH_SOLUTIONS]: [
    // AI in Law (Re-checked and expanded)
    "Current and emerging applications of AI in the Indian legal industry (research, drafting, prediction)?",
    "How can AI tools effectively assist with legal research, case law analysis, and due diligence?",
    "Ethical considerations and challenges of using AI in legal decision-making and client advice.",
    "What are the liability risks associated with AI-powered legal advice or document generation tools?",
    "Impact of AI on e-discovery processes: Predictive coding, document review.",
    "Legal validity and recognition of AI-generated legal documents or contracts in India.",
    "How can Indian law firms and legal departments practically leverage AI for improved efficiency?",
    "Data privacy and confidentiality concerns when using AI-based legal tech solutions with client data.",
    "Strategies to ensure fairness, transparency, and mitigate bias in legal AI algorithms.",
    "Future trends and predictions for AI adoption in the Indian legal practice.",
    "What is 'explainable AI' (XAI) and its importance in legal tech?",
    "How can AI be used for contract review and analysis (e.g., identifying risky clauses)?",
    "What are Large Language Models (LLMs) and their specific applications/risks in law?",
    "Regulatory landscape for AI in India: Any specific laws or guidelines for legal AI?",
    "Can AI assist in predicting litigation outcomes? What are the limitations?",
    // Legal Tech Product Development (Re-checked and expanded)
    "IP protection strategies (patents, copyright, trade secrets) for a new legal tech product.",
    "How to protect the source code, algorithms, and unique features of a legal tech solution?",
    "Key regulatory compliances for a legal tech startup in India (company law, tax, data privacy).",
    "Drafting robust User Agreements (EULA, Terms of Service, SLA) for a legal tech platform.",
    "Essential data security standards (e.g., ISO 27001) for legal tech products handling sensitive information.",
    "Ensuring compliance with DPDP Act, 2023 for a SaaS-based legal tech product.",
    "Common challenges and strategies for marketing and selling legal tech to Indian law firms.",
    "How to structure effective pilot programs or beta testing for a new legal tech solution?",
    "Key features and differentiators of successful Contract Lifecycle Management (CLM) tools.",
    "Technical and legal considerations for API integrations in legal tech products.",
    "What are the challenges in developing multilingual legal tech solutions for India?",
    "How to incorporate user feedback effectively in legal tech product development cycles?",
    "What are the specific needs of in-house legal departments vs. law firms for tech solutions?",
    "How to approach pricing and subscription models for legal tech products?",
    "What are the legal implications of using third-party AI models in a legal tech product?",
    // Data Privacy & Security in Legal Tech (Re-checked and expanded)
    "Specific data privacy risks and vulnerabilities for legal tech companies handling client matters.",
    "Implementing 'Privacy by Design' and 'Security by Design' principles in legal tech development.",
    "Data localization requirements for legal tech services storing Indian client data.",
    "Conducting a Data Protection Impact Assessment (DPIA) for a new legal tech solution.",
    "Best practices for encrypting and securing client data on a legal tech platform (at rest, in transit).",
    "Developing and testing an incident response plan for data breaches in a legal tech company.",
    "Implications of GDPR for Indian legal tech companies with EU clients or data subjects.",
    "Common cybersecurity threats targeting legal tech solutions and law firms (phishing, ransomware).",
    "Ensuring ethical data handling and anonymization in legal analytics and AI training datasets.",
    "Role and responsibilities of a Data Protection Officer (DPO) in a legal tech firm under DPDP Act.",
    "What are secure software development lifecycle (SSDLC) practices for legal tech?",
    "How to manage vendor risk for third-party components or services used in legal tech?",
    "What are the client expectations regarding data security from their legal tech providers?",
    "How to demonstrate compliance with data protection regulations to clients and auditors?",
    "What are the specific challenges of securing data in cloud-based legal tech applications?",
    // E-Discovery & Legal Operations (Re-checked and expanded)
    "Detailed overview of the e-discovery process (EDRM model) in the Indian context.",
    "Comparison of common e-discovery tools and technologies available in India.",
    "Legal best practices for data preservation (legal hold) and collection of electronic evidence.",
    "Standards for admissibility and authentication of electronic evidence under Indian Evidence Act.",
    "How can technology enhance efficiency and effectiveness of Legal Operations (Legal Ops)?",
    "Key Performance Indicators (KPIs) for measuring legal department efficiency using technology.",
    "Selection criteria and implementation process for a Matter Management or Case Management System.",
    "Role of technology (e-billing, spend analytics) in managing outside counsel spend and budget.",
    "Automating routine legal tasks (document generation, compliance tracking) using tech.",
    "Benefits and implementation of document automation tools for law firms/legal departments.",
    "What is 'Technology Assisted Review' (TAR) in e-discovery?",
    "How to manage cross-border e-discovery challenges (data privacy, blocking statutes)?",
    "What is forensic data collection and when is it required?",
    "How to create an effective e-discovery playbook for an organization?",
    "What is 'Legal Project Management' and how can tech support it?",
    // ODR & Smart Contracts (Re-checked and expanded)
    "What is Online Dispute Resolution (ODR)? Various models (e-negotiation, e-mediation, e-arbitration).",
    "Benefits, challenges, and adoption status of ODR in the Indian justice system.",
    "Which types of disputes are most suitable for resolution through ODR platforms?",
    "Legal validity and enforceability of ODR outcomes (settlements, awards) in India.",
    "How can technology (AI, video conferencing) make access to justice more effective via ODR?",
    "What are Smart Contracts? How are they technically created and deployed (e.g., on blockchain)?",
    "Current legal position on the enforceability of Smart Contracts under Indian contract law.",
    "Practical risks, limitations, and dispute resolution mechanisms for Smart Contracts.",
    "Applications of Blockchain technology in the legal field beyond smart contracts (e.g., IP registry, evidence).",
    "Regulatory considerations and potential hurdles for widespread adoption of Smart Contracts in India.",
    "What are Decentralized Autonomous Organizations (DAOs) and their legal implications?",
    "How do oracles work in the context of smart contracts?",
    "What are the challenges in coding legal nuances into smart contracts?",
    "What is the 'Digital Rupee' (CBDC) and its potential impact on smart contracts/payments?",
    "What are Non-Fungible Tokens (NFTs) and their legal/IP implications?",
    // Adoption, Ethics & Future Trends (Re-checked and expanded)
    "Ethical guidelines and professional conduct rules for lawyers using legal technology in India.",
    "Strategies for effective change management when implementing new legal tech in a firm/department.",
    "Impact of legal tech on the traditional law firm business model and lawyer roles.",
    "Essential digital skills and competencies for lawyers in a tech-driven legal environment.",
    "How can legal tech be leveraged to improve 'Access to Justice' for marginalized communities?",
    "Current investment trends and government initiatives supporting the legal tech sector in India.",
    "Key challenges and opportunities for legal tech startups in the Indian market.",
    "What is 'RegTech' (Regulatory Technology) and its intersection with Legal Tech?",
    "Potential impact of Quantum Computing on legal tech, data security, and cryptography.",
    "Predictions for the evolution of legal tech and its integration into legal practice in next 5-10 years.",
    "Methodologies for evaluating the Return on Investment (ROI) of legal technology adoption.",
    "Security and compliance considerations for using cloud-based legal tech solutions.",
    "Ensuring interoperability and data exchange standards between different legal tech tools.",
    "Role of Legal Process Outsourcing (LPO) and Alternative Legal Service Providers (ALSPs) in the tech ecosystem.",
    "How legal tech can streamline compliance management, risk assessment, and reporting.",
    "Legal and ethical implications of using Generative AI (like ChatGPT) for drafting legal documents or advice.",
    "Ensuring data sovereignty and compliance with cross-border data regulations when using global legal tech.",
    "Designing effective training programs for legal professionals on new legal tech tools.",
    "Affordable and impactful legal tech solutions for small law firms and solo practitioners in India.",
    "Cybersecurity best practices specifically tailored for law firms adopting various legal technologies.",
    "How legal tech addresses challenges of document version control, audit trails, and knowledge management.",
    "Rise of 'No-Code' or 'Low-Code' platforms for building custom legal applications.",
    "Using legal tech for managing and analyzing large intellectual property (IP) portfolios.",
    "Ethical rules regarding client communication, confidentiality, and privilege when using tech platforms.",
    "Due diligence process for selecting and vetting third-party legal tech vendors.",
    "How legal tech solutions can assist with KYC, AML, and other regulatory screening processes.",
    "Role of legal tech in managing legal spend and improving predictability of legal costs.",
    "How is legal tech being utilized in the Indian eCourts project and virtual hearings?",
    "Privacy and ethical considerations when using legal analytics tools on public/private case data.",
    "Using legal tech for automated monitoring of regulatory changes and alerts.",
    "Potential biases in legal tech AI tools (data, algorithmic) and strategies for mitigation.",
    "Key success factors for sustainable legal tech adoption and integration within an organization.",
    "How legal tech can facilitate cross-border legal collaboration and service delivery.",
    "Cybersecurity insurance considerations for law firms heavily reliant on legal tech.",
    "Maintaining attorney-client privilege and work product protection in a digital environment.",
    "Best practices for data migration when switching between legal tech systems.",
    "How can legal tech assist in proactive compliance and risk prevention rather than just reactive solutions?"
  ],
  [ServiceArea.CASE_LAW_ANALYSIS]: [
    // Basic Understanding & Overview
    "Summarize the key facts of this uploaded judgment.",
    "What were the main legal issues discussed in this judgment?",
    "Who were the parties involved in this case?",
    "Which court delivered this judgment and on what date?",
    "What was the final decision or order in this judgment?",
    "Briefly explain the background leading up to this case.",
    "What is the citation of this judgment?",
    "Identify the judges who delivered this opinion.",
    "Is this a civil or criminal matter? Explain why.",
    "What was the nature of the dispute (e.g., contract, tort, constitutional)?",
    "Can you provide a timeline of key events as per the judgment?",
    "Were there any dissenting opinions? If so, summarize them.",
    "What reliefs were sought by the petitioner/appellant?",
    "What reliefs were granted or denied by the court?",
    "Extract the operative part of the judgment.",
    "What is the significance of this judgment in brief?",
    "Was this an appeal? If so, from which lower court's decision?",
    "Does the judgment mention any specific statutes primarily relied upon?",
    "Identify any amicus curiae, if mentioned, and their submissions.",
    "How long is the judgment in terms of pages or paragraphs?",
    // Legal Analysis & Ratio
    "What is the ratio decidendi of this judgment?",
    "Identify any obiter dicta in this judgment.",
    "Explain the court's reasoning for its decision on the main issues.",
    "Which legal principles or doctrines were applied or discussed?",
    "What precedents (case laws) were relied upon by the court? List them.",
    "Did the court distinguish this case from any precedents? If so, how?",
    "Did the court overrule any previous decisions?",
    "How did the court interpret [specific statute/section] in this judgment?",
    "What were the main arguments advanced by the appellant/petitioner?",
    "What were the main arguments advanced by the respondent?",
    "How did the court address the arguments of each party?",
    "Does this judgment lay down any new law or clarify existing law?",
    "Analyze the jurisprudential basis of the court's decision.",
    "What standard of proof or review was applied by the court?",
    "Does the judgment discuss any constitutional provisions? If so, analyze their interpretation.",
    "Were there any questions of jurisdiction discussed? What was the finding?",
    "Does the judgment make any recommendations for law reform?",
    "Critically analyze the court's application of [specific legal test/doctrine].",
    "What is the binding value of this judgment (e.g., Supreme Court, High Court)?",
    "How does this judgment impact [specific area of law, e.g., contract law, IP law]?",
    "Were there any international law principles or foreign judgments referred to?",
    "What are the implications of this judgment for future cases?",
    "Does the judgment discuss the concept of 'natural justice' or 'due process'?",
    "How does the judgment deal with evidentiary issues, if any?",
    "What is the court's stance on public policy considerations in this case?",
    "Extract key legal propositions or statements of law from the judgment.",
    "Does the judgment refer to any Law Commission reports or academic writings?",
    "Analyze the court's approach to statutory interpretation in this case.",
    "Were there any concurrent findings by lower courts? How did this court treat them?",
    "What is the precedential weight of different parts of this judgment?",
    // Implications & Practical Application
    "What are the practical implications of this judgment for businesses in [specific sector]?",
    "How might this judgment affect ongoing litigation in similar matters?",
    "What advice would you give to a client based on this judgment regarding [specific scenario]?",
    "Does this judgment create any new compliance requirements for companies?",
    "How can this judgment be used to support an argument in [hypothetical case]?",
    "Are there any ambiguities in the judgment that might lead to future litigation?",
    "What are the potential financial implications or remedies discussed?",
    "Does the judgment provide any guidance on drafting contracts or policies?",
    "How does this judgment impact individual rights or liberties?",
    "Based on this judgment, what are the do's and don'ts for [specific activity]?",
    "Does this judgment have any impact on regulatory bodies or their functioning?",
    "What aspects of this judgment are likely to be challenged or appealed further?",
    "Does this judgment clarify any procedural aspects of litigation?",
    "How does this judgment align or conflict with other recent judgments on similar issues?",
    "What steps should a legal professional take after reading this judgment?",
    "Can you identify any policy gaps highlighted by this judgment?",
    "What are the socio-economic impacts discussed or implied by the judgment?",
    "How does this judgment affect government powers or administrative actions?",
    "Are there any specific industries or sectors most impacted by this ruling?",
    "Does the judgment offer any guidance on dispute resolution mechanisms?",
    "What are the key takeaways for legal practitioners from this judgment?",
    "Can this judgment be cited in international forums? Why or why not?",
    "What are the ethical considerations raised or addressed in this judgment?",
    "Does the judgment touch upon issues of technology or digital evidence?",
    "Are there any warnings or admonishments given by the court in this judgment?",
    // Advanced & Comparative
    "Compare the reasoning in this judgment with [another specific judgment - user to provide name/context].",
    "How does the approach in this Indian judgment compare to the approach in [foreign jurisdiction, e.g., UK, US] on similar issues?",
    "Track the evolution of law on [specific issue] leading up to this judgment.",
    "Is this judgment considered a landmark ruling? Why or why not?",
    "Identify any dissenting opinions and analyze their main points of disagreement.",
    "What academic commentary or legal scholarship exists regarding this judgment or the issues it addresses?",
    "Does this judgment reflect a particular judicial philosophy or interpretative approach?",
    "What is the broader constitutional or public law significance of this decision?",
    "How does this judgment contribute to the development of common law in India?",
    "Analyze the use of specific legal terms or maxims in the judgment.",
    "What future legal questions or challenges might arise from this judgment?",
    "How has this judgment been subsequently treated (followed, distinguished, overruled) by other courts? (Requires external knowledge if not in text)",
    "Could AI have assisted in any part of the judicial decision-making process evident here?",
    "Discuss the impact of judicial activism or restraint as seen in this judgment.",
    "How does this judgment impact the balance of power between different state organs?",
    // Document Specific Queries
    "Extract all defined terms and their definitions from this judgment.",
    "List all annexures or schedules referred to in this judgment.",
    "Find all instances where [specific name/term] is mentioned.",
    "What is the overall tone of the judgment (e.g., critical, empathetic, formal)?",
    "Are there any tables, charts, or figures in this judgment? Summarize them.",
    "Identify any sections that appear to be direct quotes from submissions or evidence.",
    "What is the word count or approximate length of the core reasoning section?",
    "Are there any typographical errors or obvious inconsistencies you can spot? (Use with caution)",
    "Convert this judgment into a plain language summary understandable by a non-lawyer.",
    "Create a structured outline or table of contents for this judgment."
  ],
};
